language: ruby
dist: trusty
sudo: required
rvm:
  - 2.3.1
before_script:
  - wget https://dl.eff.org/certbot-auto
  - chmod a+x certbot-auto
  - ./certbot-auto certontly --manual --quiet
script: bundle exec rake travis
