language: ruby
dist: trusty
sudo: required
rvm:
  - 2.3.1
before_script:
  - apt-get install python-pip python-dev libffi-dev libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev dialog
  - pip install certbot-s3front
script: bundle exec rake travis
